main/urls.py
from django.urls import path 

from .views import home , all_news , detailnews ,all_category ,category


app_name = 'main'

urlpatterns = [
    path('', home , name = 'home'),
    path('allnews/', all_news , name = 'allnews'),
    path('detail/<int:id>', detailnews , name = 'detail'),
    path('all-category', all_category , name = 'all-category'),
    path('category/<int:id>', category , name = 'category'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('main.urls' , namespace='main')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200)
    cat_img = models.ImageField(upload_to='img/')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class News(models.Model):

    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='img/')
    detail = models.TextField(max_length=400)
    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    add_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("allnews")

    def get_detail_url(self):
        return reverse("main:detail" ,args=[str(self.id)])
    
    def get_category_url(self):
        return reverse("main:category" ,args=[str(self.id)])
      

class Comment(models.Model):
    name =models.CharField(max_length=200)
    news = models.ForeignKey(News , on_delete=models.CASCADE) 
    email = models.CharField(max_length=200)
    comment=  models.TextField(max_length=400)
    status = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.name
    

main/views.py
from django.shortcuts import render
from .models import News , Category ,Comment
from django.contrib import messages
import datetime
# Create your views here.


def home(request):

    first_news=News.objects.first()
    side_news=News.objects.all()[1:4]
    three_categories=Category.objects.all()
    context = {
        'three_categories':three_categories,
        'side_news':side_news,
        'first_news':first_news ,
    }

    return render (request  , 'main/home.html' ,context )

def all_news(request):
    allnews=News.objects.all()
    return render (request  , 'main/all-news.html' ,{
        'allnews':allnews , 
    })

def detailnews(request , id):
    

    news = News.objects.get(id=id)
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        comment = request.POST['message']
        
        Comment.objects.create(
            news=news,
            name=name,
            email = email ,
            comment=comment,
            
        )
        
        messages.success(request , 'comment has benn submitted but in moderation mode')
    category = Category.objects.get(id=news.category.id)
    related_news=News.objects.filter(category=category).exclude(id=id)
    comments = Comment.objects.filter(news=news,status=True ).order_by('-id')

    return render (request , 'main/detail.html' , 
    
    {'news':news,
    'related_news':related_news,
    'category':category,
    'comments':comments,
    })
    
def all_category(request):
    cats = Category.objects.all()
    return render (request , 'main/category.html' , {
        
        'cats' : cats , 
    })
        

def category(request,id):
    
    category = Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    return render (request , 'main/category-news.html' , {
        
        'all_news' : news , 
        'category' : category ,
    })        

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Fast News</title>
    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
    <!-- Main Jquery -->
    <script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
    <!-- Bootstrap Js -->
    <script type="text/javascript" src="{% static 'vendor/bs4/bootstrap.min.js' %}"></script>
</head>

<body>
    <!-- Top News -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
        <div class="container">
            <a class="navbar-brand" href="/">Fast News</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'main:allnews' %}">All News</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:all-category' %}">All Categories</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block contetnt %}

    {% endblock %}

    <hr />
    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Back to top</a>
            </p>
            <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
            <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a
                    href="/docs/4.5/getting-started/introduction/">getting started guide</a>.</p>
        </div>
    </footer>
</body>

</html>

templates/main/all-news.html
{% extends 'base.html' %}


{% load static %}
{% block contetnt  %}
<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">All News</h3>
    <!-- News Box -->
    {% for allnew in allnews %}
    <div class="card mb-4 shadow">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="{{allnew.image.url}}" class="card-img" alt="..."
                    style="object-fit: cover; width: 100% ;height: 200px;">
            </div>
            <div class="col-md-8">
                <div class="card-body mb-3" style="object-fit: cover; width: 100% ;height: 185px">
                    <h5 class="card-title">{{allnew.title}}</h5>
                    <p class="card-text">{{allnew.detail}}</p>
                    <p class="card-text"><a href="{{allnew.get_detail_url}}" class="btn btn-sm btn-primary">Read
                            Full</a></p>
                </div>
            </div>
            <hr />
        </div>
    </div>
    {% endfor %}


</main>
{% endblock %}

templates/main/category-news.html
{% extends 'base.html' %}


{% load static %}
{% block contetnt  %}
<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
    <div class="card mb-4 shadow">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="{{news.image.url}}" class="card-img" alt="..."
                    style="object-fit: cover; width: 100% ;height: 200px;">
            </div>
            <div class="col-md-8">
                <div class="card-body mb-3" style="object-fit: cover; width: 100% ;height: 185px">
                    <h5 class="card-title">{{news.title}}</h5>
                    <p class="card-text">{{news.detail}}</p>
                    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read
                            Full</a></p>
                </div>
            </div>
            <hr />
        </div>
    </div>
    {% endfor %}


</main>
{% endblock %}

templates/main/category.html
{% extends 'base.html' %}


{% load static %}
{% block contetnt  %}

<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">All Categories</h3>
    <div class="row">
        <!-- Category Box -->
        {% for cat in cats %}
        <div class="col-md-4">
            <div class="card mb-3 shadow">
                <img src="{{cat.cat_img.url}}" class="card-img-top" alt="{{cat.title}}">
                <div class="card-body">
                    <h5 class="card-title">{{cat.title}}</h5>
                    <hr />
                    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">All News</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

templates/main/detail.html
{% extends 'base.html' %}


{% load static %}

{% block contetnt  %}
<main class="container mt-3 mb-5">
    <!-- featured news -->
    <div class="row my-3">
        <!-- Left -->
        <div class="col-md-8">
            <div class="card mb-3">
                <img src="{{news.image.url}}" class=" card-img-top" alt="News 1">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <hr />
                    <p class="card-text">{{news.detail}}</p>
                </div>
                <div class="card-footer">
                    In <a href="#">{{news.category.title}}</a>
                </div>
            </div>

            <!-- Comments -->
            <div class="card my-4">
                <h6 class="card-header">Add Comment</h6>
                <div class="card-body">
                    {% for message in messages %}
                    <p class="text-success">{{message}}</p>
                    {% endfor %}
                    <form method="post" action="/detail/{{news.id}}">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="col-md-2">Name<span class="text-danger">*</span></label>
                            <div class="col-md-10">
                                <input type="text" name="name" required class="form-control" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2">Email<span class="text-danger">*</span></label>
                            <div class="col-md-10">
                                <input type="temailext" name="email" required class="form-control" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2">Comment<span class="text-danger">*</span></label>
                            <div class="col-md-10">
                                <textarea class="form-control" name="message" required></textarea>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" />
                    </form>
                </div>
            </div>
            <!-- Previous Comments -->
            <div class="card my-4">
                <h6 class="card-header">Comments</h6>
                <div class="card-body">
                    {% for comment in comments %}
                    <blockquote class="blockquote text-right">
                        <p class="mb-0">{{comment.comment}}</p>
                        <footer class="blockquote-footer">{{comment.name}} <cite
                                title="Source Title">{{comment.email}}</cite></footer>
                    </blockquote>
                    <hr />
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Related News -->
        <div class="col-md-4">
            <h3 class="mb-3 border-bottom pb-1">From this Category</h3>
            <!-- Category Box -->
            {% for news in related_news %}
            <div class="card mb-3 shadow">
                <img src="{{news.image.url}}" class="card-img-top" alt="News 1">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <hr />
                    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a>
                    </p>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</main>

{% endblock %}

templates/main/home.html
{% extends 'base.html' %}


{% load static %}

{% block contetnt  %}
<main class="container mt-3 mb-5">
    <!-- featured news -->
    <div class="row my-3">
        <!-- Left -->
        <div class="col-md-7">
            <div class="card mb-3">
                <img src="{{first_news.image.url}}" class="card-img-top" alt="{{first_news.title}}">
                <div class="card-body">
                    <h5 class="card-title">{{first_news.title}}</h5>

                    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read
                            Full</a></p>
                </div>
            </div>
        </div>
        <!-- Right -->
        <div class="col-md-5" style="max-height: 450px; overflow: auto;">
            <!-- News Box -->

            {% for news in side_news %}
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{news.image.url}}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{news.title}}</h5>
                            <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read
                                    Full</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            {% endfor%}
            <!-- News Box -->
            <!-- <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{% static 'imgs/3.jpg' %}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
                        </div>
                    </div>
                </div>
            </div> -->
            <!-- <hr /> -->
            <!-- News Box -->
            <!-- <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{% static 'imgs/3.jpg' %}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
                        </div>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
    <!-- Category Wise News -->
    {% for category in three_categories %}
    <h3 class="border-bottom pb-1">{{category.title}} <a href="/category.php" class="float-right btn btn-sm btn-dark">In
            this
            Category</a></h3>
    <div class="row my-4">
        {% for news in category.news_set.all %}
        {% if forloop.counter > 0 %}
        <!-- News box -->
        <div class="col-md-3">
            <div class="card mb-3 shadow">
                <img src="{{news.image.url}}" class="card-img-top" alt="News 1"
                    style="object-fit: cover; width: 100% ;height: 200px;">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <hr />
                    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">nnn</a></p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
    <!-- End Single Category -->
</main>
{% endblock %}


H:\django-apps\news\src\templates\main\home.html